### ISSUE TITLE
My TV Shows

### ISSUE THREAD

**Issue by mrXoo** [ruinernin/foxymeta#11]
Hi there,

Another great addon, just what i was looking for.

I have a problem opening the MY TV Shows section. I just get the spinning wheel.

Movies works fine so I know my Trakt is good

thanks

**Comment by mrXoo** [comment]
Also just noticed that when i searched for Shameless I got an error

**Comment by ruinernin** [comment]
If you have a detailed error from the kodi log file that would be helpful to try track this down.

I've neglected this code for around a year happy to hear it's still working to any extent :sweat_smile:.

**Comment by mrXoo** [comment]
I will get this info as soon as possible

**Comment by mrXoo** [comment]
`                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'data'
                                            Traceback (most recent call last):
                                              File "C:\Users\ED\Documents\KODI\LEIA\Kodi\portable_data\addons\plugin.video.foxymeta\launcher.py", line 6, in <module>
                                                addon.run(*sys.argv[:3])
                                              File "C:\Users\ED\Documents\KODI\LEIA\Kodi\portable_data\addons\plugin.video.foxymeta\addon.py", line 109, in run
                                                router.run(url, handle, path)
                                              File "C:\Users\ED\Documents\KODI\LEIA\Kodi\portable_data\addons\plugin.video.foxymeta\resources\lib\router.py", line 136, in run
                                                func(**kwargs)
                                              File "C:\Users\ED\Documents\KODI\LEIA\Kodi\portable_data\addons\plugin.video.foxymeta\resources\lib\tv.py", line 105, in search
                                                li = ui.show_listitem(trakt_data=show)
                                              File "C:\Users\ED\Documents\KODI\LEIA\Kodi\portable_data\addons\plugin.video.foxymeta\resources\lib\ui.py", line 59, in show_listitem
                                                art['poster'] = metadata.tvdb_poster(trakt_data['ids']['tvdb'])
                                              File "C:\Users\ED\Documents\KODI\LEIA\Kodi\portable_data\addons\plugin.video.foxymeta\resources\lib\router.py", line 112, in wrapper
                                                result = func(*args, **kwargs)
                                              File "C:\Users\ED\Documents\KODI\LEIA\Kodi\portable_data\addons\plugin.video.foxymeta\resources\lib\metadata.py", line 202, in tvdb_poster
                                                path = tvdb_show(tvdbid)['poster']
                                              File "C:\Users\ED\Documents\KODI\LEIA\Kodi\portable_data\addons\plugin.video.foxymeta\resources\lib\router.py", line 51, in wrapper
                                                result = func(*args, **kwargs)
                                              File "C:\Users\ED\Documents\KODI\LEIA\Kodi\portable_data\addons\plugin.video.foxymeta\resources\lib\metadata.py", line 130, in tvdb_show
                                                result = tvdb.get(path)['data']
                                            KeyError: 'data'
                                            -->End of Python script error report<--`
this was when i search for shameless under tv shows

**Comment by mrXoo** [comment]
[log.txt](https://github.com/ruinernin/foxymeta/files/5780038/log.txt)

**Comment by mrXoo** [comment]
this next one is the busy when i click on my TV Shows
[log spinning wheel.txt](https://github.com/ruinernin/foxymeta/files/5780056/log.spinning.wheel.txt)
